In [1]:
import numpy as np
import time
import sys

The file contains all of the integers between 1 and 10,000 (inclusive, with no repeats) in unsorted order.  The integer in the i^{th}i 
th
  row of the file gives you the i^{th}i 
th
  entry of an input array.

 Your task is to compute the total number of comparisons used to sort the given input file by QuickSort.  As you know, the number of comparisons depends on which elements are chosen as pivots, so we'll ask you to explore three different pivoting rules.

You should not count comparisons one-by-one.  Rather, when there is a recursive call on a subarray of length m, you should simply add m-1 to your running total of comparisons.  (This is because the pivot element is compared to each of the other m-1 elements in the subarray in this recursive call.)


1)
For the first part of the programming assignment, you should always use the first element of the array as the pivot element.

2)
Compute the number of comparisons (as in Problem 1), always using the final element of the given array as the pivot element.  Again, be sure to implement the Partition subroutine exactly as it is described in the video lectures.

3)
Compute the number of comparisons (as in Problem 1), using the "median-of-three" pivot rule.  [The primary motivation behind this rule is to do a little bit of extra work to get much better performance on input arrays that are nearly sorted or reverse sorted.]  In more detail, you should choose the pivot as follows.  Consider the first, middle, and final elements of the given array.  (If the array has odd length it should be clear what the "middle" element is; for an array with even length 2k, use the k^{th}
  element as the "middle" element. So for the array 4 5 6 7,  the "middle" element is the second one ---- 5 and not 6!)  Identify which of these three elements is the median (i.e., the one whose value is in between the other two), and use this as your pivot.  As discussed in the first and second parts of this programming assignment, be sure to implement Partition exactly as described in the video lectures (including exchanging the pivot element with the first element just before the main Partition subroutine).

EXAMPLE: For the input array 8 2 4 5 7 1 you would consider the first (8), middle (4), and last (1) elements; since 4 is the median of the set {1,4,8}, you would use 4 as your pivot element.

## 1) Quick sort using first pivot

In [51]:
def quickSort(data,pivotMethod='random'):
    # Need this function to initialize the left and right bounds. There may be a smarter way to do this
    left = 0
    right = len(data)-1
    comparisons,data = quickSortCall(data,left,right,pivotMethod)
    return comparisons,data

def quickSortCall(data,left,right,pivotMethod='random'):
    if len(data) == 1:
        comparisons = 0
        return comparisons,data
    if left < right:
        # Pick pivot index
        comparisonsPartition,data,p = partition(data,left,right,pivotMethod)
        comparisonsLeft,data = quickSortCall(data,left,p-1,pivotMethod)
        comparisonsRight,data = quickSortCall(data,p+1,right,pivotMethod)
        comparisons = comparisonsLeft+comparisonsRight+comparisonsPartition
    else:
        comparisons = 0
    return comparisons,data



# Test case https://www.coursera.org/learn/algorithms-divide-conquer/discussions/weeks/3/threads/fG_c7gxREeiFUgpNZCwT4A
def partition(data,left,right,pivotMethod='random'):
    
    if pivotMethod.lower() == 'first':
        # Pick left most as pivot
        pivot = data[left]
        pivotIndex = left
    elif pivotMethod.lower() == 'last':
        pivot = data[right]
        pivotIndex = right
    elif pivotMethod.lower() == 'random':
        np.random.seed(1)
        pivotIndex = np.random.randint(left,right+1)
        pivot = data[pivotIndex]
    else:
        # Get first, last, and middle element
#         print(data)
        if right-left == 1:
            middle = left
            pivot = data[left]
            pivotIndex = left
        else:
            middle = int(np.ceil((right-left+1)/2)-1)+left
            medianOfThree = np.array([data[middle],data[left],data[right]])
            for ii in range(3):
                if (medianOfThree[ii] >  min(medianOfThree)) and (medianOfThree[ii] < max(medianOfThree)):
                    pivot = medianOfThree[ii]
                    pivotIndex = np.array([middle,left,right])[ii]
#             print(data[left],data[right],data[middle],pivot)

    # Swap because we may have picked an element from the middle of the array, carry on as normal
    data[pivotIndex],data[left] = data[left],data[pivotIndex]
    
    # Partial Sort
    i = left+1
    for j in range(left+1,right+1):
        if data[j] < pivot: # swap i and j and increment
            data[i],data[j] = data[j],data[i]
            i+=1

    # Swap pivot position
    data[left],data[i-1] = data[i-1],data[left]
    comparisons = (right-left)
    p = i-1
#     print(comparisons)
    return comparisons,data,p


In [52]:
data = np.loadtxt('QuickSortArray.txt')
# data = np.sort(data)
t1 = time.time()
comparisons,data = quickSort(data,pivotMethod='first')
comparisons,data,time.time()-t1

(162085,
 array([1.000e+00, 2.000e+00, 3.000e+00, ..., 9.998e+03, 9.999e+03,
        1.000e+04]),
 0.05605125427246094)

In [53]:
#Check it is right
min(np.diff(data)),max(np.diff(data))

(1.0, 1.0)

In [54]:
np.random.seed(1)
np.random.randint(4,7)

5

## 2) Quick sort using last pivot

In [55]:
data = np.loadtxt('QuickSortArray.txt')
t1 = time.time()
comparisons,data = quickSort(data,pivotMethod='last')
comparisons,data,time.time()-t1

(164123,
 array([1.000e+00, 2.000e+00, 3.000e+00, ..., 9.998e+03, 9.999e+03,
        1.000e+04]),
 0.05404949188232422)

In [56]:
#Check it is right
min(np.diff(data)),max(np.diff(data))

(1.0, 1.0)

## 3) Quick sort using the median of 3 rule

In [57]:
# This works with sorted data much much better
# data = [2, 20, 1, 15, 3, 11, 13, 6, 16, 10, 19, 5, 4, 9, 8, 14, 18, 17, 7, 12] # Test data
t1 = time.time()
data = np.loadtxt('QuickSortArray.txt')
# data = np.sort(data)
comparisons,data = quickSort(data,pivotMethod='median')
comparisons,data,time.time()-t1

(138382,
 array([1.000e+00, 2.000e+00, 3.000e+00, ..., 9.998e+03, 9.999e+03,
        1.000e+04]),
 0.10309338569641113)

In [58]:
#Check it is right
min(np.diff(data)),max(np.diff(data))

(1.0, 1.0)

## Just for fun lets try random

In [59]:
data = np.loadtxt('QuickSortArray.txt')
# data = np.sort(data)
t1 = time.time()
comparisons,data = quickSort(data,pivotMethod='random')
comparisons,data,time.time()-t1

(157643,
 array([1.000e+00, 2.000e+00, 3.000e+00, ..., 9.998e+03, 9.999e+03,
        1.000e+04]),
 0.07807135581970215)

In [60]:
#Check it is right
min(np.diff(data)),max(np.diff(data))

(1.0, 1.0)

In [61]:
data = np.loadtxt('QuickSortArray.txt')
t1 = time.time()
data = np.sort(data)
time.time()-t1

0.0

In [64]:
# Compare to merge sort for fun. Similar performance with the first and last options being faster, but those suffer if the dat ais ordered, so random and median seem like a good alternative
# Merge sort was ~0.83 sec, and quick sort is ~0.6-0.9
data = np.loadtxt('IntegerArray.txt')
t1 = time.time()
comparisons,data = quickSort(data,pivotMethod='random')
comparisons,data,time.time()-t1

(2046746,
 array([1.0000e+00, 2.0000e+00, 3.0000e+00, ..., 9.9998e+04, 9.9999e+04,
        1.0000e+05]),
 0.9098284244537354)